### ISSUE TITLE
Fail to generate the panorama of the scene (422 Unprocessable Entity)

### ISSUE THREAD

**Issue by TainanKyle** [qwang666/RoomTex-#2]
Thank you for your nice work.

I encountered an issue while trying to install and run the model in your repository. I followed the steps in the installation guide, but I am experiencing an error at "Generate the panorama of the scene".

**Error Message**
The following error appears when I try to run the command:
```
Traceback (most recent call last):
  File "gene_img/pano/pano_text2img.py", line 121, in <module>
    image = gene_text2img(cfg, url)
  File "gene_img/pano/pano_text2img.py", line 108, in gene_text2img
    image = re_img(cfg, depth_path, url)
  File "gene_img/pano/pano_text2img.py", line 99, in re_img
    results = r['images']
KeyError: 'images'
```

And the error message appears at the `stable-diffusion-webui` is:
```
"POST /sdapi/v1/txt2img HTTP/1.1" 422 Unprocessable Entity
```

I don't know how to solve this problem. Could you give me some guidance?

**Comment by william1065** [comment]
Hi,I wonder if you've solve it? i meet it too.could you please give me some advice? @TainanKyle # #

**Comment by sculmh** [comment]
Same issue, can't resolve it. @2018001187 @TainanKyle
